# Generated by Django 6.0.2 on 2026-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phoneimage'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['brand'], name='phones_phon_brand_b10d18_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['price'], name='phones_phon_price_840fd3_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['created_at'], name='phones_phon_created_3a00b4_idx'),
        ),
    ]
